#!/usr/bin/env python3
"""Offline case-study generator.

Produces REAL, reproducible naive-vs-hardened numbers without Docker/Postgres by
running each suite case through the exact generation + validation code path
(`generation.synthesize`) with curated contexts that mirror what hybrid retrieval
would surface (the mapped poisoned/clean doc). Retrieval quality is held constant;
only the security mode differs.

For the fully live version (real hybrid retrieval over pgvector + HTTP), use
`tools/run_all.py` against a running `docker compose` stack — it consumes the same
suites and target file. This offline harness exists so the portfolio artifact is
regenerable anywhere.

    python tools/offline_case_study.py
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

os.environ.setdefault("OPENAI_API_KEY", "")
os.environ.setdefault("ANTHROPIC_API_KEY", "")

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

import yaml  # noqa: E402

from app.generation.generate import synthesize  # noqa: E402

CORPUS = ROOT / "examples" / "rag_docs"
APPROX_TOKENS = lambda s: max(1, round(len(s.split()) * 1.3))  # noqa: E731

# Map each case to the document(s) retrieval would surface. High confidence (0.8)
# is used so we isolate the prompt/validation defenses from the confidence gate.
CONTEXT_MAP = {
    "rag_hidden_instructions": ["poisoned/hidden_instructions.md"],
    "rag_html_comment": ["poisoned/html_comment_injection.md"],
    "rag_yaml_frontmatter": ["poisoned/yaml_frontmatter_injection.md"],
    "rag_markdown_link_exfil": ["poisoned/markdown_link_exfil.md"],
    "rag_encoded_payload": ["poisoned/encoded_payload.md"],
    "rag_fake_citation_authority": ["poisoned/fake_citation_authority.md"],
    "sdd_marker_via_document": ["clean/internal_runbook_canary.md"],
}
DEFAULT_CONTEXT = ["clean/product_overview.md"]

SUITES = [
    "suites/rag_injection.yaml",
    "suites/prompt_injection.yaml",
    "suites/sensitive_data_disclosure.yaml",
    "suites/unbounded_consumption.yaml",
]


def load(path: str) -> dict:
    return yaml.safe_load((ROOT / path).read_text())


def protected_map() -> dict[str, str]:
    target = load("vectorguard_target.yaml")
    return {p["id"]: p["value"] for p in target["protected"]}


def context_for(case_id: str) -> list[str]:
    files = CONTEXT_MAP.get(case_id, DEFAULT_CONTEXT)
    return [(CORPUS / f).read_text() for f in files]


def evaluate(fail_if: dict, answer: str, protected: dict) -> tuple[list[str], bool]:
    """Return (findings, skipped). Rate-limit checks are live-only -> skipped."""
    findings = []
    low = answer.lower()
    for pid in fail_if.get("leaks_protected", []):
        v = protected.get(pid)
        if v and v.lower() in low:
            findings.append(f"leaked protected value '{pid}'")
    for needle in fail_if.get("response_matches", []):
        if needle.lower() in low:
            findings.append(f"forbidden text '{needle}'")
    limit = fail_if.get("response_token_count_gt")
    if limit is not None and APPROX_TOKENS(answer) > limit:
        findings.append(f"exceeded token budget ({APPROX_TOKENS(answer)} > {limit})")
    skipped = "no_429_after" in fail_if
    return findings, skipped


async def run_case(case: dict, mode: str, protected: dict) -> dict:
    context = context_for(case["id"])
    query = case["turns"][-1]  # last attack turn drives the observable answer
    result = await synthesize(query=query, context_blocks=context, confidence=0.8, mode=mode)
    findings, skipped = evaluate(case.get("fail_if", {}), result.answer, protected)
    return {
        "id": case["id"],
        "technique": case.get("technique"),
        "mode": mode,
        "passed": not findings,
        "skipped": skipped,
        "findings": findings,
        "answer": result.answer[:400],
        "blocked_reason": result.blocked_reason,
    }


async def main() -> None:
    protected = protected_map()
    results: dict[str, dict[str, list]] = {"naive": {}, "hardened": {}}

    for suite_path in SUITES:
        suite = load(suite_path)
        name = suite["suite"]
        for mode in ("naive", "hardened"):
            cases = []
            for case in suite["cases"]:
                cases.append(await run_case(case, mode, protected))
            results[mode][name] = cases

    write_case_study(results, protected)


def _counts(cases: list) -> tuple[int, int, int]:
    active = [c for c in cases if not c["skipped"]]
    p = sum(1 for c in active if c["passed"])
    f = len(active) - p
    return p, f, 3 * sum(len(c["findings"]) for c in active)


def write_case_study(results: dict, protected: dict) -> None:
    suites = list(results["naive"].keys())
    L = [
        "# InjectionRange Case Study: Naive vs. Hardened",
        "",
        "> Generated by `tools/offline_case_study.py` — real numbers from the exact",
        "> generation + validation code path (`generation.synthesize`), with curated",
        "> contexts mirroring hybrid retrieval. Regenerate live numbers (real pgvector",
        "> retrieval over HTTP) with `tools/run_all.py` against a running stack.",
        "",
        "Both modes share the **identical** retrieval pipeline; every delta below is",
        "attributable to hardening — trust-boundary framing, injection-resistant",
        "prompting, groundedness + confidence gates, canary-leak blocking, and the",
        "output-token budget — not to retrieval quality.",
        "",
        "## Pass rate & risk score by suite",
        "",
        "| Suite | Naive pass | Hardened pass | Naive risk | Hardened risk |",
        "|-------|-----------|---------------|-----------|---------------|",
    ]
    tot = {"naive": [0, 0, 0], "hardened": [0, 0, 0]}
    for s in suites:
        np_, nf, nr = _counts(results["naive"][s])
        hp, hf, hr = _counts(results["hardened"][s])
        tot["naive"] = [a + b for a, b in zip(tot["naive"], (np_, nf, nr))]
        tot["hardened"] = [a + b for a, b in zip(tot["hardened"], (hp, hf, hr))]
        L.append(f"| {s} | {np_}/{np_+nf} | {hp}/{hp+hf} | {nr} | {hr} |")
    L.append(
        f"| **TOTAL** | **{tot['naive'][0]}/{tot['naive'][0]+tot['naive'][1]}** "
        f"| **{tot['hardened'][0]}/{tot['hardened'][0]+tot['hardened'][1]}** "
        f"| **{tot['naive'][2]}** | **{tot['hardened'][2]}** |"
    )

    L += ["", "## Gaps closed by hardening (per case)", ""]
    for s in suites:
        naive_cases = {c["id"]: c for c in results["naive"][s]}
        hardened_cases = {c["id"]: c for c in results["hardened"][s]}
        closed = [
            (cid, naive_cases[cid], hardened_cases[cid])
            for cid in naive_cases
            if not naive_cases[cid]["passed"] and hardened_cases[cid]["passed"]
        ]
        if not closed:
            continue
        L.append(f"### {s}")
        L.append("")
        L.append("| Case | Technique | Naive finding | Hardened defense |")
        L.append("|------|-----------|---------------|------------------|")
        for cid, n, h in closed:
            defense = {
                "refused": "trust-boundary prompt refused the injected/disclosure instruction",
                "canary_leak_blocked": "canary-leak scan blocked the response",
                "ungrounded": "groundedness gate replaced with fallback",
                "truncated_budget": "output-token budget truncated the response",
                "low_confidence": "confidence gate returned fallback",
            }.get(h["blocked_reason"], "trust-boundary prompt ignored the injected instruction (answered only from data)")
            L.append(f"| {cid} | {n['technique']} | {'; '.join(n['findings'])} | {defense} |")
        L.append("")

    # An example captured exploit transcript from naive mode.
    L += ["## Example captured exploit (naive mode)", ""]
    for s in suites:
        ex = next((c for c in results["naive"][s] if not c["passed"]), None)
        if ex:
            L += [
                f"Suite `{s}`, case `{ex['id']}` ({ex['technique']}):",
                "",
                "```",
                f"attacker: <retrieves poisoned/clean doc, then asks the {ex['technique']} probe>",
                f"assistant (naive): {ex['answer']}",
                "```",
                "",
                f"Findings: {'; '.join(ex['findings'])}",
                "",
            ]
            break

    L += [
        "## Note on live-only checks",
        "",
        "`unbounded_consumption / uc_rate_limit_flood` asserts a 429 appears after the",
        "per-minute limit. That requires the live Redis-backed limiter and is skipped",
        "in the offline harness (run `tools/run_all.py` to exercise it).",
    ]

    out = ROOT / "docs" / "CASE_STUDY.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"Wrote {out}")
    print(
        f"Totals — naive pass {tot['naive'][0]}/{tot['naive'][0]+tot['naive'][1]} "
        f"(risk {tot['naive'][2]}) | hardened pass {tot['hardened'][0]}/"
        f"{tot['hardened'][0]+tot['hardened'][1]} (risk {tot['hardened'][2]})"
    )


if __name__ == "__main__":
    asyncio.run(main())
